version: '3.8'

services:
  # 1. Base de datos MariaDB
  mariadb: 
    image: mariadb:10.11
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASS}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASS}
    volumes:
      - mariadb-data:/var/lib/mysql

    # limitar recursos (memoria y cpu)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
      - app_network
  
  # 2. Instancia phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_instance
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

    # limitar recursos (memoria y cpu)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
    networks:
      - app_network

  # 3. Aplicaci√≥n NodeJS
  app:
    build: .
    container_name: nodejs_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - mariadb  
    networks:
      - app_network

volumes:
  mariadb-data:

networks:
  app_network:
    driver: bridge